name: CI/CD Pipeline for Node.js Book API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.diegosantuccione }}
          password: ${{ secrets.BlaXs2004 }}

      - name: Build Docker image
        run: |
          docker build . -t diegosantuccione/esame-api:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push diegosantuccione/esame-api:latest
